### ISSUE TITLE
MIUI安全组件

### ISSUE THREAD

**Issue by IJustWantANamePlease** [LittleChest/Storage-Isolation-Rules#5]
### 规则状态

- [x] 规则已存在

### 设置 JSON：

```shell
{
  "device_info": {
    "api": 31,
    "manufacturer": "Xiaomi",
    "locale": "zh-CN"
  },
  "verified": false,
  "behaviors": [
    "@abuse"
  ],
  "recommendation": "@recommended",
  "non_standard_files": [
    ".turing.dat",
    ".turingdebug",
    "DCIM/.tmfs"
  ],
  "package": "com.miui.guardprovider",
  "last_update": {
    "target_api": 30,
    "flags": "read_storage, write_storage",
    "timestamp": 1658670605,
    "version_code": 138,
    "version_name": "1.3.8"
  }
}
```

### 补充必要的信息：

会在根目录和DCIM生成奇怪的东西，在酷安搜到了阴谋论但不知真假
隔离完正常使用了几天，暂时没发现任何异常

**Comment by LittleChest** [comment]
已完成 感谢

**Comment by ArthurCyy** [comment]
@LittleChest 这条先回退一下，在最新MIUI开发版自带的MIUI安全组件（版本1.4.5）中已暂未发现非标准行为
![Screenshot_2022-09-09-09-21-56-938_moe shizuku redirectstorage-edit](https://user-images.githubusercontent.com/37627147/189252520-9221963f-40e3-47a8-99b8-a5fe23ba27ef.jpg)

**Comment by IJustWantANamePlease** [comment]
emmm我觉得这就要取决于内测版的应用是否算做最新发行版了，我不建议回退（~~因为我用的正式版~~），不过MIUI应用本来就混乱也不知道怎么样才算“内测”…
要不开个投票吧，刚好小箱做了投票功能😏

**Comment by LittleChest** [comment]
> emmm我觉得这就要取决于内测版的应用是否算做最新发行版了，我不建议回退（~因为我用的正式版~），不过MIUI应用本来就混乱也不知道怎么样才算“内测”… 要不开个投票吧，刚好小箱做了投票功能😏

也不是不行 但是看它的人真的很少（

**Comment by LittleChest** [comment]
加了个提示 等待MIUI更新

**Comment by LittleChest** [comment]
在讨论中加了个投票，有兴趣可以去看看鸭
